using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ASPNETCoreMVC.Migrations
{
    /// <inheritdoc />
    public partial class SecondMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "_title",
                table: "_tasks",
                type: "nvarchar(150)",
                maxLength: 150,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.InsertData(
                table: "_tasks",
                columns: new[] { "_id", "_content", "_created_At", "_title" },
                values: new object[] { 1, "Autogenerated content", new DateTime(2022, 11, 11, 15, 58, 51, 895, DateTimeKind.Local).AddTicks(9805), "Autogenerated Title" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "_tasks",
                keyColumn: "_id",
                keyValue: 1);

            migrationBuilder.AlterColumn<string>(
                name: "_title",
                table: "_tasks",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(150)",
                oldMaxLength: 150);
        }
    }
}
