using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ASPNETCoreMVC.Migrations
{
    /// <inheritdoc />
    public partial class Third : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "_tasks",
                columns: new[] { "_id", "_content", "_created_At", "_title" },
                values: new object[] { 2, "Autogenerated content", new DateTime(2022, 11, 11, 16, 8, 47, 266, DateTimeKind.Local).AddTicks(8375), "Autogenerated Title" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "_tasks",
                keyColumn: "_id",
                keyValue: 2);
        }
    }
}
