using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ASPNETCoreMVC.Migrations
{
    /// <inheritdoc />
    public partial class Fifth : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "_tasks",
                columns: new[] { "_id", "_content", "_created_At", "_title" },
                values: new object[] { 1, "Autogenerated content", new DateTime(2022, 11, 13, 12, 59, 34, 460, DateTimeKind.Local).AddTicks(585), "Autogenerated Title" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "_tasks",
                keyColumn: "_id",
                keyValue: 1);
        }
    }
}
